#!/bin/bash

# List of executables to remove
declare -A files
files["draw"]="draw"
files["text"]="text"
files["main"]="main"

# Remove each executable
for executable in "${files[@]}"; do
    if [ -f $executable ]; then
        rm $executable
        echo "Removed $executable"
    else
        echo "$executable does not exist"
    fi
done
